### PR TITLE
heading_ids_spaces_to_dash feature for compatibility with github mark…

### PR DESCRIPTION
**Pull request by hoytech**
…down, and others

### CODE REVIEW

**Comment by briandfoy** [comment]
Okay, I see this. Give me a bit of time to check it out. It looks good though.

**Comment by hoytech** [comment]
Thanks!

For context, I want this so my table-of-contents generator script works unchanged between github and when I render it myself:  https://github.com/hoytech/md-toc

FWIW I'm hacking it like this for now:

```
INIT {
    ## MultiMarkdown doesn't turn "-"s into spaces
    ## FIXME: Remove if https://github.com/briandfoy/text-multimarkdown/pull/1 merged

    *Text::MultiMarkdown::_Header2Label = sub {
        my ($self, $header) = @_;
        my $label = lc $header;
        $label =~ s/ +/-/g;
        $label =~ s/[^A-Za-z0-9:_.-]//g;        # Strip illegal characters
        while ($label =~ s/^[^A-Za-z]//g)
            {};     # Strip illegal leading characters
        return $label;
    };
}
```

**Comment by briandfoy** [comment]
I'm likely busy until the end of the month, but there's one thing that can help. If you could create a test where you check the result with and without the change, 

* make a markdown file or string
* convert it without the new feature using the old code. That should stay the same in the new code.
* convert it again with the new feature, using the new code. You should see what you want.

Not a big deal, but this is something I'd like to add for new features and why I need some time to look at it.

**Comment by briandfoy** [comment]
I'll fix up the things I mentioned.

**Comment by hoytech** [comment]
Thank you! Sorry I didn't get around to fixing those things -- too much else on my plate right now. :)

**Comment by briandfoy** [comment]
This feature is now released in 1.002, which should show up on MetaCPAN within the hour.

**Pull request merged**
